version: '3.8'

services:
  api-movies:
    build:
      context: ./
      dockerfile: Dockerfile
    image: api-movies
    container_name: api-movies
    restart: unless-stopped
    ports:
      - "8000:8000"
